/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CmdRegisterImpl */

#ifndef _Included_CmdRegisterImpl
#define _Included_CmdRegisterImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef CmdRegisterImpl_serialVersionUID
#define CmdRegisterImpl_serialVersionUID -3215090123894869218i64
#undef CmdRegisterImpl_serialVersionUID
#define CmdRegisterImpl_serialVersionUID -4100238210092549637i64
#undef CmdRegisterImpl_serialVersionUID
#define CmdRegisterImpl_serialVersionUID 4974527148936298033i64
/*
 * Class:     CmdRegisterImpl
 * Method:    getlocaltime
 * Signature: (LGetLocalTime;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_CmdRegisterImpl_getlocaltime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CmdRegisterImpl
 * Method:    getversion
 * Signature: (LGetVersion;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_CmdRegisterImpl_getversion
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
